nx659j: Add missing wfd lib
Fixes Process: com.qualcomm.wfd.service:wfd_service, PID: 22505
java.lang.UnsatisfiedLinkError: dlopen failed: library "libwfdnative.so" not found

Change-Id: I747ee6d74c73d2330fcad391aa524fca9216c668